### ISSUE TITLE
Markdown joiner crashes (Fatal Windows exception, code 0xc0000005 - PhantomJS has crashed.)

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/markdown-joiner#10]
After running markdown joiner with the exemplary output from:
"https://github.com/Open-Systems-Pharmacology/QualificationPlan/tree/master/examples/minimal"

I get the following error:

C:\projects\Internal\PEQ\Github\Qualification-programs\markdown-joiner>npm run start -- -i "C:\Projects\test\Qualificati
onPlan-master\examples\minimal\reporting_engine_output" -o "C:\Projects\test\QualificationPlan-master\examples\minimal\r
eport"

> @ospsuite/markdown-joiner@1.0.0 start C:\projects\Internal\PEQ\Github\Qualification-programs\markdown-joiner
> node ./src/index.js "-i" "C:\Projects\test\QualificationPlan-master\examples\minimal\reporting_engine_output" "-o" "C:
\Projects\test\QualificationPlan-master\examples\minimal\report"

internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: Command failed: C:\projects\Internal\PEQ\Github\Qualification-programs\markdown-joiner\node_modules\phantomjs-pre
built\lib\phantom\bin\phantomjs.exe C:\projects\Internal\PEQ\Github\Qualification-programs\markdown-joiner\node_modules\
markdown-pdf\phantom\render.js C:\Users\gemuh\AppData\Local\Temp\tmp-6224UR9N26NGs0VQ.html C:\Users\gemuh\AppData\Local\
Temp\tmp-6224Iqpkn8xnH1Hb.pdf C:\projects\Internal\PEQ\Github\Qualification-programs\markdown-joiner C:\projects\Interna
l\PEQ\Github\Qualification-programs\markdown-joiner\src\helpers\running-t.js C:\projects\Internal\PEQ\Github\Qualificati
on-programs\markdown-joiner\src\styles\pdf-styles.css C:\projects\Internal\PEQ\Github\Qualification-programs\markdown-jo
iner\node_modules\markdown-pdf\css\highlight.css Letter portrait 2cm 0 10000
Fatal Windows exception, code 0xc0000005.
PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ospsuite/markdown-joiner@1.0.0 start: `node ./src/index.js "-i" "C:\Projects\test\QualificationPlan-master\exa
mples\minimal\reporting_engine_output" "-o" "C:\Projects\test\QualificationPlan-master\examples\minimal\report"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ospsuite/markdown-joiner@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gemuh\AppData\Roaming\npm-cache\_logs\2019-06-04T07_28_49_383Z-debug.log

**Comment by Incei** [comment]
Although this is shifted to Milestone 3, could we move this to an earlier stage?
I cannot work on my local machine due to this error. 

the current alternative is VERY time-consuming, considering the amounts of qualifications im performing...:The external machine I'm using instead, where it does work, does not have internet connection, nor does it have PDF reader....I thefore also cannot commit from there to github and have to copy each step back to my local machine. etc. etc....

**Comment by Incei** [comment]
just FYI if this speeds up the issue finding: despite the error , everything runs trough, the only problem i see in the output is that the pdf is 0mb (corrupt), all other files and folders are created correctly.

**Comment by msevestre** [comment]
There is actually nothing we can do for this error. It is due to a faulty laptop configuration. Reinstalling graphic card drivers has helped in the past apparently. 
Since you are not using the PDF generated by the joiner anyways, not a big deal correct?

**Comment by Incei** [comment]
@msevestre: many thanks for this info. 

Correct, but I will always get an error during the workflow run and manually need to start the markdown-merger at the end. I can live with this (just tested if everything else works). In that case we can close this issue (since we cant fix it ? ) , and i will do the last step manually until i get a new laptop.

**Comment by Incei** [comment]
Updated graphics card, and problem is solved!! @msevestre many thanks!
