### ISSUE TITLE
Add support for github Superscript for Mardown <sup> and <sub>

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/markdown-joiner#24]
I have used the superscript script for MD <sup></sup>, which works for MD but after converting to PDF the  <sup></sup>text pops-up also e.g as follows:
Eq. 1: GMFE=10<sup>(Σ|log10(pred PK parameter∕obs PK parameter)|)∕n</sup>

**Comment by msevestre** [comment]
>I have used the superscript script for MD. which works for MD

What superscript are you talking about. If this is not standard MD it won't be supported out of the box by other tool using markdown
Is it supported by Github for example?

**Comment by Incei** [comment]
it is supported by github

**Comment by Incei** [comment]
i have applied an alternative text for now, but generally would be good to have... and looks much more professional

**Comment by msevestre** [comment]
What superscript are you talking about. 

How is the syntax?

GMFE=10(Σ|log10(pred PK parameter∕obs PK parameter)|)∕n does not do anything for me on github

**Comment by Incei** [comment]
GMFE=10<sup>(Σ|log10(pred PK parameter∕obs PK parameter)|)∕n</sup>

**Comment by msevestre** [comment]
Asking for the 3rd time 

# What superscript are you talking about.

Where is this superscript specified :)

**Comment by Incei** [comment]
text '<sup>' text <'/sup>'

**Comment by msevestre** [comment]
so it's only one command? <sup>. Interesting

**Comment by Incei** [comment]
it doesnt work becuase the script automatically converts in github .(obviously)...here is the link

https://github.com/getgrav/grav/issues/1672

**Comment by Incei** [comment]
sry for the confusion..

**Comment by msevestre** [comment]
Ok got it. 
I think we could probably do something for it when the markdown is being parsed somehow. We create an html that is then converted to markdown so applying the right "class" would do the trick

**Comment by msevestre** [comment]
I have converted the title to show the feature request

**Comment by Incei** [comment]
reading back..it is actually funny.. :)

**Comment by msevestre** [comment]
see #32 PDF will now be creaeted using typora. If typora supports this, it will work
