### ISSUE TITLE
Tables "merged" together

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/markdown-joiner#26]
when creating report for https://github.com/Open-Systems-Pharmacology/QualificationPlan/tree/master/examples/PKRatio

Tables on the last page are displayed just as one big table.
RE output and report attached.
[output.pdf](https://github.com/Open-Systems-Pharmacology/markdown-joiner/files/3411350/output.pdf)

![grafik](https://user-images.githubusercontent.com/25061876/61540267-96b9d980-aa3d-11e9-8f1e-846deaf052c1.png)
[re_output.zip](https://github.com/Open-Systems-Pharmacology/markdown-joiner/files/3411348/re_output.zip)

**Comment by msevestre** [comment]
see #32 PDF will now be creaeted using typora. If typora supports this, it will work
