### ISSUE TITLE
Combine md-output of markdown-joiner into a single md

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/markdown-joiner#32]
As the currently created pdf via markdown-joiner is a bit limited, we have decided to create a pdf via export-function in typora.

For this we first need to merge all MD-files into 1 MD file, therefore we created 2 matlab-scripts for this.

Would like to ask whether these scripts can be merged with the scripts for qualification runner, qualification workflow, and markdown-joiner in sequential order using 1 single qualification-workflow-script in the reporting engine.

The scripts are attached (matlab files renamed to txt)
[func_MD_merger.txt](https://github.com/Open-Systems-Pharmacology/markdown-joiner/files/3519170/func_MD_merger.txt)
[Main_Merge.txt](https://github.com/Open-Systems-Pharmacology/markdown-joiner/files/3519171/Main_Merge.txt)

update: this issue is fixed under: 
[Fixes #234 Combine md-output of markdown-joiner into a single md #236](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/236)

Update: included in reporting engine and released:
[https://github.com/Open-Systems-Pharmacology/Reporting-Engine/releases/tag/v3.0.1.36 ](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/releases/tag/v3.0.1.36 )

**Comment by Yuri05** [comment]
>The scripts are attached (matlab files renamed to txt)
func_MD_merger.txt
Main_Merge.txt

Integrated into RE:
https://github.com/Open-Systems-Pharmacology/Reporting-Engine/blob/develop/src/code/qualification/auxiliaries/mergeQualificationMarkdown.m

**Comment by msevestre** [comment]
@Incei Can you explain what the code is doing? It seems that some html is being inserted and some # are being replaced.  It is definitely more than just file concatenation am I correct?

ALso it adds some words such as "final input parameters" etc etc.. Very very hard to understand. 

Also why are you changing the font size? Are you working with markdown (e.g. size is a meta data of the markdown processor)

So please explain what needs to be done when joining the markdown and we will implement this feature

Also: Are we going to use the pdf generated by the markdown joiner or is this not required anymore? In that case, I would simplify the code to not have to deal with this

Happy to have a phone call to clarify what needs to be done

**Comment by Incei** [comment]
@msevestre, Lets have a phone call. I will setup a meeting. :)
