### ISSUE TITLE
Summary.md : '/' in the links becomes '%5c' on github

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/markdown-joiner#33]
When publishing the mardown output folder to be used in github as markdown version:

The table of content folder (Summary.md) in this Markdown folder contains the links to the respective chapter subfolders. 
e.g. 
https://github.com/Incei/Raltegravir-Model/blob/master/evaluation/report-output/markdown/001_1_Introduction\001_1_Introduction.md

Unfortunately as you can see the last dash is in the opposite direction and somehow after uploading to github, the last '/' in the links becomes '%5c' and therefore doens't work anymore.

@msevestre @Yuri05  can we solve this? (fyi not urgent for the workshop as currently the pdf is the most important aim.

@sfrechen @janschlender

**Comment by msevestre** [comment]
obsolete
