### ISSUE TITLE
Title has to be excluded from the table of contents, and makes large title fonts

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/markdown-joiner#34]
The title page should have larger fonts, and not be included in the table of content.

**Comment by msevestre** [comment]
@Incei I don't undersand what needs to be done here. Do we still need this?

**Comment by Incei** [comment]
@Yuri05 do we still need to work on this, or will we apply the script of Sulav as it is...?

**Comment by Incei** [comment]
(in short, yes we defenitally want the title excluded from the table of contencs, and we want to have larger title fonts, in case this is now implemented, than this issue is obsolete ) :)

**Comment by msevestre** [comment]
Title of what? Sorry I am not sure what we are talking about

And no the script should not be used. Very soon, Matlab won't be supported
anymore.(at least that's what we agreed upon at the end of August)

Can't you simply use ## as required to define titles?

**Comment by Incei** [comment]
@Yuri05  please support here!

**Comment by msevestre** [comment]
Can you explain what title you are referring to?

Simply attached a makrdown output from the joiner and let me know what
should not be in the TOC

Since we are generating it, we have full freedom

**Comment by Incei** [comment]
Actually exactly as it says: 
- REPORT title should not be in the table of contents (if it is already not in there, perfect)
- the REPORT title should be in larger fonts than standard text size (if adding ##, then it became part of TOC when using [TOC] option in typora, if not anymore, perfect)

Many thanks,

**Comment by msevestre** [comment]
Fixed with #32
