### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/markdown-joiner#50]
MarkdownJoiner 1.2.0.6 crashes with the error
`Unable to generate markdown. fs.copyFileSync is not a function`
Something missing in the setup?
Reporting Engine output attached, but is probably a general problem.
[re_output.zip](https://github.com/Open-Systems-Pharmacology/markdown-joiner/files/4404341/re_output.zip)

**Comment by msevestre** [comment]
Is this after the update of this morning? How did you use the markdown joiner?

**Comment by msevestre** [comment]
The only real way of using it is via NPM as node module. anything else is a workaround that may or may not work, in particular with creating an exe

**Comment by Yuri05** [comment]
>Is this after the update of this morning?

nope, same problem with 1.2.0.5

>How did you use the markdown joiner?

from matlab (`MarkdownJoiner_path `is the full path of markdown-joiner.exe):
`status = system(['"' MarkdownJoiner_path '" -i "' REOutput_path '" -o "' ReportOutput_path '"']); 
`

**Comment by msevestre** [comment]
With which version did this start? 
It is possible that we will not be able to use the exe anymore if this does not work

**Comment by Yuri05** [comment]
started with 1.2.0.5
1.1.0.8 worked (and there were no successfull builds between 1.1.0.8 and 1.2.0.5)

Maybe something wrong with node.js paths (s. https://github.com/jsdoc/jsdoc/issues/1671)?

**Comment by msevestre** [comment]
We embed node in the exe as a workaround. No idea why this is not working.

**Comment by msevestre** [comment]
Which is a very bad idea to begin with. I'd strongly suggest to install node on the machine and the package globally and simply call it. It would remove a lot of headaches

**Comment by msevestre** [comment]
yeah. I can build locally but it does not work on the server. I have no idea why

**Comment by msevestre** [comment]
Trying to use another node version..

**Comment by Yuri05** [comment]
With 1.2.0.7 (using re_output attached in this issue):
```
internal/assert.js:14
    throw new ERR_INTERNAL_ASSERTION(message);
    ^

Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

[90m    at assert (internal/assert.js:14:11)[39m
[90m    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:129:3)[39m
[90m    at internal/main/run_main_module.js:7:1[39m {
  code: [32m'ERR_INTERNAL_ASSERTION'[39m
}
```

**Comment by msevestre** [comment]
wow. OK going to try with another node version...

**Comment by msevestre** [comment]
@Yuri05 
* Node 11 does not work
* Node 10 does not work

I tried with v8.12 x64 which is what I have on my machine. Can you try and see if this works?

**Comment by msevestre** [comment]
https://ci.appveyor.com/project/open-systems-pharmacology-ci/markdown-joiner/build/artifacts

**Comment by Yuri05** [comment]
hmm, with this one I don't get any error, but created reports are not markdown but something different
[report.zip](https://github.com/Open-Systems-Pharmacology/markdown-joiner/files/4415766/report.zip)

**Comment by Yuri05** [comment]
looking at the  file header of report.md: seems to be compressed 
![grafik](https://user-images.githubusercontent.com/25061876/78149147-ef979980-7435-11ea-8ce8-a676abd10d9b.png)

**Comment by msevestre** [comment]
WHAT???

**Comment by msevestre** [comment]
Ok I have no idea. Can you just install node and use the node module? This is a real waste of my time

**Comment by msevestre** [comment]
I am using the same version of node on my machine

**Comment by msevestre** [comment]
Can you copy your input folder so that I can try locally?

**Comment by Yuri05** [comment]
input folder is attached in the issue description.
Also suddenly with MD-Joiner 1.1 I get the same crap. Maybe smthg wrong on my comp now..

**Comment by msevestre** [comment]
Just tried on my machine. No problem at all...

**Comment by msevestre** [comment]
Tried with the exe created by appveyor and also with the exe created locally. 
[re_output_output_dist.zip](https://github.com/Open-Systems-Pharmacology/markdown-joiner/files/4415835/re_output_output_dist.zip)

**Comment by Yuri05** [comment]
hmm, must be my comp then. interesting... LEt's merge for now, will test later on another machine

**Comment by msevestre** [comment]
can't reproduce.
