### ISSUE TITLE
Titles are only listed in table of contents and not in main body

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/markdown-joiner#7]

**Comment by msevestre** [comment]
@Yuri05 @sfrechen  Looking at this bug. In all the example we have, the section `title` is also in the content file. 
We need to decide what we want to do here. Either we remove the section title from the content file and we can add it dynamically, or we keep the current implementation and do not add the section title as part of the content file. 

Right now, the implementation is consistent with the example files created in the QualificationPlan repository

Please advise as what you want to do

**Comment by msevestre** [comment]
@sfrechen @Yuri05 
An example of the report generated if I add the section title at the beginning of the content file
Very hard to tell for me what way is better from the "modeller" point of view. 

[output.pdf](https://github.com/Open-Systems-Pharmacology/markdown-joiner/files/3242031/output.pdf)

**Comment by Yuri05** [comment]
>We need to decide what we want to do here. Either we remove the section title from the content file and we can add it dynamically, or we keep the current implementation and do not add the section title as part of the content file.

I think we should "_remove the section title from the content file and we can add it dynamically_".
For now I would always add it.
_Later_ we can think about an option per section in a qualification plan telling if it should be added or not.

@sfrechen @incei please comment

**Comment by msevestre** [comment]
Ok this will be implemented as described
