### ISSUE TITLE
Create Portable Setup

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/markdown-joiner#8]

**Comment by msevestre** [comment]
Why would we want to do something like that?
It is an npm package that can be install globally with one command

**Comment by Yuri05** [comment]
Once MD-Joiner is released and distributed: Yes.
But in the test phase between releases (like now) beta-testers have to download the repository in order to work with the latest development version of MD-joiner

**Comment by msevestre** [comment]
They only have to clone once and then do git pull to get the latest version. 
It cannot be any easier than that

**Comment by Yuri05** [comment]
well, with a portable setup testers don't need to install git...

**Comment by msevestre** [comment]
But they need to install node!

**Comment by msevestre** [comment]
done https://ci.appveyor.com/project/open-systems-pharmacology-ci/markdown-joiner/build/artifacts
